apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler-service
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scheduler-service
  template:
    metadata:
      labels:
        app: scheduler-service
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - docker-desktop
      terminationGracePeriodSeconds: 10
      containers:
        - name: scheduler-service
          image: scheduler-service:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: "100m"
              memory: "400Mi"
            limits:
              cpu: "500m"
              memory: "2Gi"
          ports:
            - containerPort: 8080
              protocol: TCP
              name: http
          env:
            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  name: mongo
                  key: username
            - name: MONGO_PASS
              valueFrom:
                secretKeyRef:
                  name: mongo
                  key: password