server:
  port: 8080
  servlet:
    context-path: /scheduler

spring:
  application:
    name: scheduler-service
  profiles:
    active: dev
  mvc:
    throw-exception-if-no-handler-found: true
  jackson:
    date-format: com.fasterxml.jackson.databind.util.StdDateFormat
    time-zone: Asia/Shanghai
    deserialization:
      fail-on-unknown-properties: false
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb+srv://${MONGO_USER:user}:${MONGO_PASS:pass}@core.migjs4v.mongodb.net/?retryWrites=true&w=majority}
      database: ${MONGO_DATABASE:core}
      authentication-database: ${MONGO_AUTH_DATABASE:admin}

  cloud:
    kubernetes:
      discovery:
        all-namespaces: true
      config:
        name: scheduler-service
        fail-fast: true
