server:
  port: ${SERVER_PORT:8080}
  compression:
    enabled: true

spring:
  application:
    name: ${SPRING_APPLICATION_NAME:scheduler-service}
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  mvc:
    throw-exception-if-no-handler-found: true
  jackson:
    date-format: com.fasterxml.jackson.databind.util.StdDateFormat
    time-zone: Asia/Shanghai
    deserialization:
      fail-on-unknown-properties: false
  # data:
  #   mongodb:
  #     uri: ${MONGO_URI:mongodb+srv://${MONGO_USER:user}:${MONGO_PASS:pass}@core.migjs4v.mongodb.net/?retryWrites=true&w=majority}
  #     database: ${MONGO_DATABASE:core}
  #     authentication-database: ${MONGO_AUTH_DATABASE:admin}

logging:
  level:
    root: ${LOGGING_LEVEL_ROOT:INFO}
  file:
    name: logs/${spring.application.name}.log
  logback:
    rollingpolicy:
      clean-history-on-start: false

management:
  server:
    port: ${ADMIN_PORT:8081}
  endpoint:
    health:
      enabled: true
    startup:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,startup,refresh