apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scheduler-service
  template:
    metadata:
      labels:
        app: scheduler-service
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - docker-desktop
      terminationGracePeriodSeconds: 10
      containers:
        - name: scheduler-service
          image: scheduler-service:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: "100m"
              memory: "400Mi"
            limits:
              cpu: "500m"
              memory: "2Gi"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: admin
              containerPort: 8081
              protocol: TCP
          env:
            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  name: mongo
                  key: username
            - name: MONGO_PASS
              valueFrom:
                secretKeyRef:
                  name: mongo
                  key: password
          livenessProbe:
            httpGet:
              path: "/actuator/health/liveness"
              port: admin
            initialDelaySeconds: 30
            failureThreshold: 3
            periodSeconds: 5
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: "/actuator/health/readiness"
              port: admin
            initialDelaySeconds: 30
            failureThreshold: 3
            periodSeconds: 60
            timeoutSeconds: 5
          startupProbe:
            httpGet:
              path: "/actuator/startup"
              port: admin
            initialDelaySeconds: 15
            failureThreshold: 30
            periodSeconds: 10
            timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: scheduler-service
  annotations:
    boot.spring.io/actuator: http://:8081/actuator
spec:
  type: ClusterIP
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: scheduler-service